[phases.setup]
# Force installation Node
nixpkgs = ["nodejs_18"]

# DÃ©sactive l'installation automatique (cause d'erreur)
[phases.install]
cmds = []

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "mkdir -p backend/public && cp -R frontend/dist/* backend/public",
  "cd backend && npm install && npm run build"
]

[start]
cmd = "cd backend && npm start"
